# Bathy SLAM params
submap_size: 500 # nbr_pings per submap
add_gaussian_noise: false

# Submap overlaps
overlap_coverage: 0.9 # Reduce submap area to look for overlap by this factor


# GICP registration params (meters)
gicp_max_correspondence_distance: 10
gicp_maximum_iterations: 100
gicp_transform_epsilon: 1e-4
gicp_euclidean_fitness_epsilon: 1e-4
gicp_ransac_outlier_rejection_threshold: 1
gicp_normal_search_radius: 20

# DR weights - uncertainty on vehicle navigation across submap
dr_noise_x: 3.
dr_noise_y: 3.
dr_noise_z: 1e-4
dr_noise_roll: 1e-4
dr_noise_pitch: 1e-4
dr_noise_yaw: 1e-4

# Loop closure edge covariance computation method
# 0 = fixed external value
# 1 = manual inputs (#TODO: factor out to YAML file)
# 2 = covariances from GICP
# 3 = covariances loaded from external file
lc_edge_covs_type: 2